
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.aiguess.realtimePriceService.entity
    
#配置日志
logging:
  #配置日志文件路径
  ## 本地  默认spring.log
  #path: C:\soft\apache-tomcat-8.0.50\logs
  ## 线上
  
  #制定名称  采用相对路径方式将日志文件输出到【log\realtimePriceService.log】
  ## dev 
  # file: C:\soft\apache-tomcat-8.0.50\logs\realtimePriceService.log
  
  ## 线上
  file: /opt/tomcat/logs/ocrItem.log
  
  level:
    #xatu.zsl: info #不同目录下的日志可配置不同级别, 开发模式用debug
    com.aiguess.realtimePriceService.controller: debug
#    com.aiguess.realtimePriceService.controller: info
    #org.springfromework.web: info



  security:
    basic:
      enabled: false # 启用SpringSecurity的安全配置项
    user:
      name: root  # 认证用户名
      password: root # 认证密码
      role: User       # 授权角色